### ISSUE TITLE
layout of bar graph

### ISSUE THREAD

**Issue by erika061538** [erika061538/sds192-mp2#1]
1. The texts on x-axis for the plot that shows that number of candidates in each state overlap one another.
2. Besides democratic candidates, I think we can also plot number of republican candidates in each state as well.

**Comment by vnguyen259** [comment]
Good points! I think plotting the number of democratic and republican candidates with the colors red and blue might be good too. Do you want us to try that?

**Comment by erika061538** [comment]
I just tried to do that. I added the num of republican candidates in each state to the same plot.

**Comment by vnguyen259** [comment]
Thanks! I think I have figured out the overlapping labels too.
